import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    apartments: "Apartments",
    marketplace: "Marketplace",
    about: "About",
    contact: "Contact",
    signIn: "Sign In",
    signUp: "Sign Up",
    welcomeBack: "Welcome back! Sign in to continue",
    createYourAccount: "Create your account to get started",
    heroTitle:
      "Find Your Perfect Place Near Campus — Safe, Verified, and Student-Friendly.",
    heroSubtitle:
      "Simplify your housing search with verified listings and trusted landlords",
    startSearching: "Start Searching",
    verifiedRentals: "Verified Rentals",
    campusHousing: "Campus Housing",
    affordableHousing: "Affordable Student Housing",
    aboutUs: "About Us",
    aboutUsText:
      "Welcome to UniNest — your trusted student-housing hub. We connect university students with safe, verified housing near campus. Explore personalized matching and filters that fit your budget and lifestyle. Start your next chapter with confidence.",
    ourOffers: "Our Offers",
    readyTitle: "Ready to find your next home?",
    builtForStudents: "Built for students by students",
    weUnderstand: "We understand what campus life needs",
    home: "Home",
    aboutUsLink: "About Us",
    connect: "Connect",
    rightsReserved: "©2025 All rights reserved",
    email: "Email",
    password: "Password",
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    student: "Student",
    landlord: "Landlord",
    admin: "Admin",
    superadmin: "SuperAdmin",
    studentId: "Student ID",
    university: "University",
    selectUniversity: "Select your university",
    forgotPassword: "Forgot Password?",
    sendResetCode: "Send Reset Code",
    resetLinkSent: "If this email exists, a reset code was sent.",
    noAccount: "You don't have an account?",
    createOne: "Create one",
    passwordAgain: "Password Again",
    haveAccount: "Have an account?",
    logIn: "Log In",
    marketplaceTitle: "MARKETPLACE",
    marketplaceSubtitle: "Student Living Made Simple: Find, Verify, Move In.",
    searchPlaceholder: "Search here",
    lastListings: "Last Listings",
    offers: "Offers",
    favorites: "Favorites",
    masonry: "Masonry",
    postAd: "Post AD",
    filters: "Filters",
    price: "Price",
    squareMeter: "Square Meter",
    availableIn: "Available in",
    garage: "Garage",
    yes: "Yes",
    no: "No",
    rooms: "Rooms",
    partner: "Partner",
    ownerOfBuilding: "Owner of the building",
    ownerOfProperty: "Property Owner",
    messageNow: "Message Now",
    beds: "beds",
    baths: "bath",
    kitchen: "Kitchen",
    livingRoom: "ILR",
    overview: "Overview",
    startingFrom: "Starting from",
    myProfile: "My Profile",
    logout: "Logout",
    signInRequired: "Sign In Required",
    logInRequired: "Log In Required",
    pleaseSignInToMessage: "Please sign in to message the property owner.",
    pleaseSignInToAddFavorite: "Please sign in to add properties to your favorites list.",
    pleaseSignInToViewFavorites: "Please sign in to view your favorites.",
    pleaseSignInToPostAd:
      "Please sign in to your account to post an ad and connect with students.",
    signingIn: "Signing In...",
    creatingAccount: "Creating Account...",
    createAdComingSoon: "Create ad functionality coming soon!",
    propertyNotFound: "Property not found",
    backToMarketplace: "Back to Marketplace",
    profile: "Profile",
    loadingProfile: "Loading profile...",
    failedToLoadProfile: "Failed to load profile",
    goHome: "Go Home",
    profileUpdated: "Profile updated successfully!",
    contactInformation: "Contact Information",
    personalInformation: "Personal Information",
    studentInformation: "Student Information",
    profilePicture: "Profile Picture",
    firstNameRequired: "First name is required",
    lastNameRequired: "Last name is required",
    invalidPhone: "Invalid phone number format",
    gender: "Gender",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    selectGender: "Select Gender",
    genderMale: "Male",
    genderFemale: "Female",
    preferredLanguageLabel: "Preferred Language",
    languageEnglish: "English",
    languageFrench: "French",
    languageArabic: "Arabic",
    avatarUrlLabel: "Avatar URL",
    avatarUrlPlaceholder: "https://example.com/avatar.jpg",
    preview: "Preview:",
    phonePlaceholder: "e.g., +1 (555) 123-4567",
    enterFirstName: "Enter first name",
    enterLastName: "Enter last name",
    studentIdLabel: "Student ID",
    studentIdPlaceholder: "Enter your student ID",
    notProvided: "Not provided",
    notSpecified: "Not specified",
    notAssigned: "Not assigned",
    ratings: "Ratings",
    averageRating: "Average Rating",
    totalReviews: "Total Reviews",
    accountCreated: "Account created",
    lastUpdated: "Last updated",
    deleteAccount: "Delete account",
    deleteAccountWarning:
      "Permanently deletes your account and all associated data. This action cannot be undone.",
    delete: "Delete",
    deleteAccountBullet1: "Removes conversations, favorites, and listings.",
    deleteAccountBullet2: "You will be signed out immediately.",
    Delete: "Delete",
    // Alert Modals
    deleteProfilePictureTitle: "Delete profile picture",
    deleteProfilePictureMessage: "This will remove your current picture. The change only applies after you click Save Changes.",
    confirm: "Confirm",
    // Admin Page
    city: "City",
    domain: "Domain",
    latitude: "Latitude",
    longitude: "Longitude",
    deleteUniversityMessage: "This action cannot be undone. Are you sure you want to delete this university?",
    saving: "Saving...",
    adding: "Adding...",
    save: "Save",
    add: "Add",
    verified: "Verified",
    addUniversity: "Add University",
    editUniversity: "Edit University",
    universityName: "University Name",
    deleteUniversity: "Delete University",
    updateDetails: "Update the details below",
    fillDetails: "Fill in the details below",
    // Auth Alerts
    accountCreatedTitle: "Account Created!",
    accountCreatedMessage: "Your account has been created successfully. Please sign in to continue.",
    signInNow: "Sign In Now",
    ctaBrowseSubtitle:
      "Browse hundreds of verified student-friendly apartments and find your perfect home today",
    // About Page
    ourMission: "Our Mission",
    missionParagraph:
      "We exist to remove friction from student housing. No more endless social feed posts or unreliable landlord chains. UniNest centralizes trusted listings, transparent pricing and simple communication—so you can focus on your studies and campus life.",
    missionPoint1: "Verified listings & fair pricing transparency.",
    missionPoint2: "Tools that match lifestyle (quiet, social, partner-ready).",
    missionPoint3: "Support for international & first-year students.",
    missionPoint4: "Inclusive approach to budget & accessibility needs.",
    coreValues: "Core Values",
    howItWorks: "How It Works",
    startExploring: "Start Exploring",
    hiwDiscoverTitle: "Discover",
    hiwDiscoverDesc: "Browse verified, student-friendly listings near campus.",
    hiwCompareTitle: "Compare",
    hiwCompareDesc:
      "Filter by budget, distance, amenities and roommate options.",
    hiwConnectTitle: "Connect",
    hiwConnectDesc: "Message owners securely and schedule viewings fast.",
    hiwMoveInTitle: "Move In",
    hiwMoveInDesc: "Start your semester settled, confident and prepared.",
    // Contact Page
    contactSubtitle:
      "We'd love to hear from you—questions, suggestions or partnership ideas.",
    sendMessageHeading: "Send a Message",
    nameLabel: "Name",
    emailLabel: "Email",
    messageLabel: "Message",
    namePlaceholder: "Your name",
    emailPlaceholder: "you@example.com",
    messagePlaceholder: "Tell us how we can help...",
    sendMessage: "Send Message",
    sent: "Sent!",
    privacyNotice:
      "We reply within 24h (weekdays). Your data is only used to respond to this inquiry.",
    orEmailDirectly: "Or email us directly",
    contactInfo: "Contact Information",
    supportLabel: "Support",
    responseTimeLabel: "Response time",
    supportHours: "Sunday - Thursday",
    usualResponse: "We typically respond within 24 hours.",
    faqs: "FAQs",
    faqQ1: "How are listings verified?",
    faqA1:
      "We manually review ownership docs & run consistency checks before publishing.",
    faqQ2: "Can I schedule a tour?",
    faqA2:
      "Yes. Use the message feature on a listing to request viewing times directly.",
    faqQ3: "Do you support roommate matching?",
    faqA3: "We're introducing a matching beta soon—stay tuned!",
    messageSentSuccess: "Message sent successfully!",
    // About Feature Descriptions
    aboutDesc1: "Trust & safety first in every listing we verify.",
    aboutDesc2: "Designed for student life: proximity, community, balance.",
    aboutDesc3: "Affordability matters—options for different budgets.",
    // Forgot Password
    forgotPasswordInstructions: "Enter your email address and we'll send you a code to reset your password.",
    rememberPassword: "Remember your password?",
    backToSignIn: "Back to Sign In",
    // Header
    theme: "Theme",
    language: "Language",
    dark: "Dark",
    light: "Light",
    english: "English",
    arabic: "Arabic",
    notifications: "Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No notifications yet.",
    messages: "Messages",
    noConversations: "No conversations yet.",
    conversation: "Conversation",
    noMessagesYet: "No messages yet",
    messageOptions: "Message options",
    deleteMessage: "Delete message",
    deleteMessageConfirm: "Are you sure you want to delete this message? This action cannot be undone.",
    messageDeleted: "Message deleted",
    loading: "Loading...",
    loadingApartments: "Loading apartments...",
    loadingProperty: "Loading property...",
    loadingMarketplace: "Loading marketplace...",
    loadingMessages: "Loading messages...",
    loadingUniversities: "Loading universities...",
    // Profile Page
    uploadPicture: "Upload Picture",
    dangerZone: "Danger Zone",
    administration: "Administration",
    universities: "Universities",
    adminManagement: "Admin Management",
    manageAdminUsers: "Manage admin users and permissions",
    createAdmin: "Create Admin",
    adminUsers: "Admin Users",
    noAdminsFound: "No admin users found",
    fillAdminDetails: "Fill in the admin user details",
    creating: "Creating...",
    create: "Create",
    deleteAdmin: "Delete Admin",
    deleteAdminMessage: "Are you sure you want to delete this admin user? This action cannot be undone.",
    name: "Name",
    role: "Role",
    createdAt: "Created",
    actions: "Actions",
    accountMenu: "Account menu",
    guestMenu: "Guest menu",
    // Apartments Page - Filters & Listings
    clearAll: "Clear all",
    min: "Min",
    max: "Max",
    allCities: "All cities",
    showingResults: "Showing",
    properties: "properties",
    tryAgain: "Try again",
    noListingsFound: "No listings found",
    tryAdjustingFilters: "Try adjusting your filters or search query",
    clearFilters: "Clear filters",
    failedToLoadListings: "Failed to load listings",
    failedToCreateAd: "Failed to create ad",
    fillRequiredFields: "Please fill in all required fields",
    maxImagesError: "Maximum 10 images per listing",
    canAddMoreImages: "You can add",
    moreImages: "more image(s)",
    failedToLoadUniversities: "Failed to load universities",
    propertyListing: "Property Listing",
    // Map & Location
    location: "Location",
    showOnMap: "Show on Map",
    distance: "Distance",
    mapView: "Map",
    gridView: "Grid",
    propertyLocation: "Property Location",
    searchLocation: "Search for an address...",
    selectedLocation: "Selected Location",
    locationPickerHint: "Click on the map or search for an address to set the property location",
    propertiesOnMap: "properties on map",
    // Listing Duration
    listingDuration: "Listing Duration",
    listingDurationHint: "How long the listing will be visible",
    "1week": "1 Week",
    "2weeks": "2 Weeks",
    "1month": "1 Month",
    "2months": "2 Months",
    "3months": "3 Months",
    expiresAt: "Expires at",
    renewListing: "Renew Listing",
    listingExpired: "Listing Expired",
    listingRenewed: "Listing renewed successfully",
    month: "mo",
    Apartment: "Apartment",
    House: "House",
    Room: "Room",
    Studio: "Studio",
    // Universities Management Page
    universitiesManagement: "Universities Management",
    manageUniversityInfo: "Manage university information and locations",
    universityCity: "City",
    universityDomain: "Domain",
    universityLatitude: "Latitude",
    universityLongitude: "Longitude",
    clickRowToEdit: "Tip: click any university row to open edit/delete actions.",
    confirmDeleteUniversity: "Are you sure you want to delete this university?",
    universityDeleted: "University deleted successfully",
    universityUpdated: "University updated successfully",
    universityCreated: "University created successfully",
    noUniversitiesFound: "No universities found",
    distanceToUniversityMeters: "Distance to university (meters)",
    autoCalculated: "Auto-calculated from map",
    // Filters & Post Ad
    applyFilters: "Apply Filters",
    maxOccupants: "Max Occupants",
    maxOccupantsHint: "Maximum number of people allowed",
    "Size (m²)": "Size (m²)",
    imagesRequired: "At least one image is required",
    imageUploadFailed: "Failed to upload images",
    viewAllImages: "View all images",
    images: "images",
    image: "image",
    mark360: "360°",
    "360Image": "360° Panorama",
    // My Listings Page
    myListings: "My Listings",
    manageYourProperties: "Manage your property listings",
    postNewAd: "Post New Ad",
    noListingsYet: "No listings yet",
    startByCreating: "Start by creating your first property listing",
    createListing: "Create Listing",
    visible: "Visible",
    hidden: "Hidden",
    view: "View",
    edit: "Edit",
    hide: "Hide",
    show: "Show",
    confirmDelete: "Confirm Delete",
    deleteListingConfirm: "Are you sure you want to delete this listing? This action cannot be undone.",
    editListing: "Edit Listing",
    title: "Title",
    description: "Description",
    pricePerMonth: "Price/Month",
    propertyType: "Property Type",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    size: "Size",
    distanceToUniversity: "Distance to University",
    leaseDuration: "Lease Duration",
    dismiss: "Dismiss",
    listingBasics: "Listing Basics",
    listingTitle: "Listing Title",
    pricingDetails: "Pricing & Details",
    monthlyPrice: "Monthly Price",
    // Password Change
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    sendVerificationCode: "Send Verification Code",
    verificationCode: "Verification Code",
    passwordWillBeEmailed: "A secure password will be generated and sent to the admin's email",
    passwordChangedSuccessfully: "Password changed successfully",
    verificationCodeSent: "Verification code sent to your email",
    enterVerificationCode: "Enter the 6-digit code sent to your email",
    passwordMustMatch: "Passwords must match",
    passwordTooShort: "Password must be at least 6 characters",
    updateYourPassword: "Update your account password",
    clickToSendCode: "Click the button below to receive a verification code via email",
    // Roommate Matching
    roommates: "Roommates",
    findRoommates: "Find Roommates",
    roommateProfile: "Roommate Profile",
    roommateProfileSubtitle: "Set your preferences to find compatible roommates",
    findRoommatesSubtitle: "Connect with compatible students looking for roommates",
    loadingRoommates: "Loading roommates...",
    budgetPreferences: "Budget Preferences",
    minBudget: "Minimum Budget",
    maxBudget: "Maximum Budget",
    livingPreferences: "Living Preferences",
    cleanlinessLevel: "Cleanliness Level",
    noiseLevel: "Noise Level",
    sleepSchedule: "Sleep Schedule",
    studyHabits: "Study Habits",
    lifestyle: "Lifestyle",
    smokingAllowed: "Smoking Allowed",
    petsAllowed: "Pets Allowed",
    guestsPolicy: "Guests Policy",
    aboutYou: "About You",
    moveInDate: "Move-in Date",
    bio: "Bio",
    bioPlaceholder: "Tell potential roommates about yourself, your interests, and what you're looking for...",
    profileActive: "Profile Active",
    profileInactive: "Profile Inactive",
    profileSaved: "Profile saved successfully!",
    profileDeactivated: "Profile deactivated",
    saveProfile: "Save Profile",
    manageMatches: "Manage Matches",
    removeMatch: "Remove",
    removeMatchConfirm: "Are you sure you want to remove this match?",
    matchRemoved: "Match removed successfully!",
    relaxed: "Relaxed",
    veryClean: "Very Clean",
    quiet: "Quiet",
    social: "Social",
    sleepEarly: "Early Bird",
    sleepNormal: "Normal",
    sleepLate: "Night Owl",
    studyHome: "At Home",
    studyLibrary: "Library",
    studyMixed: "Mixed",
    guestsNever: "Never",
    guestsSometimes: "Sometimes",
    guestsOften: "Often",
    smokingOk: "Smoking OK",
    noSmoking: "No Smoking",
    petsOk: "Pets OK",
    noPets: "No Pets",
    cleanlinessRelaxed: "Relaxed",
    cleanlinessFlexible: "Flexible",
    cleanlinessModerate: "Moderate",
    cleanlinessClean: "Clean",
    cleanlinessVeryClean: "Very Clean",
    upTo: "Up to",
    connectRoommate: "Connect",
    connecting: "Connecting...",
    search: "Search",
    matches: "Matches",
    roommatesFound: "roommates found",
    noRoommatesFound: "No roommates found",
    tryDifferentFilters: "Try adjusting your filters",
    createProfileToMatch: "Create a profile to see compatibility scores",
    createProfileHint: "Complete your roommate profile to match with others",
    createProfile: "Create Profile",
    anySleepSchedule: "Any Sleep Schedule",
    anySmoking: "Any Smoking Preference",
    pendingRequests: "Pending Requests",
    acceptedMatches: "Accepted Matches",
    sentRequests: "Sent Requests",
    compatible: "compatible",
    accept: "Accept",
    reject: "Reject",
    matched: "Matched!",
    message: "Message",
    awaitingResponse: "Awaiting response...",
    noMatchesYet: "No matches yet",
    startConnecting: "Start connecting with potential roommates",
    sendMatchRequest: "Send Match Request",
    matchRequestHint: "Send a friendly intro message to {{name}}",
    matchRequestHintPre: "Send a friendly intro message to",
    introMessagePlaceholder: "Hi! I'm looking for a roommate and thought we might be a good match...",
    sendRequest: "Send Request",
    sending: "Sending...",
    viewProfile: "View Profile",
    profileDetails: "Profile Details",
    viewDetails: "View Details",
    aboutMe: "About Me",
    // Majors & Interests
    major: "Major",
    selectMajor: "Select your major",
    interests: "Interests",
    selectInterests: "Select your interests",
    // Common Majors
    majorEngineering: "Engineering",
    majorComputerScience: "Computer Science",
    majorMedicine: "Medicine",
    majorBusiness: "Business Administration",
    majorLaw: "Law",
    majorArts: "Arts & Design",
    majorScience: "Natural Sciences",
    majorEducation: "Education",
    majorPsychology: "Psychology",
    majorCommunications: "Communications",
    majorArchitecture: "Architecture",
    majorNursing: "Nursing",
    majorOther: "Other",
    // Common Interests
    interestSports: "Sports",
    interestGaming: "Gaming",
    interestReading: "Reading",
    interestMusic: "Music",
    interestCooking: "Cooking",
    interestFitness: "Fitness",
    interestMovies: "Movies & TV",
    interestTravel: "Travel",
    interestPhotography: "Photography",
    interestArt: "Art",
    interestOutdoors: "Outdoors",
    interestTech: "Technology",
    interestFashion: "Fashion",
    interestPets: "Pets & Animals",
    interestVolunteering: "Volunteering",
    anyMajor: "Any Major",
    selected: "selected",
    // Additional Roommate & Notification Keys
    cleanliness: "Cleanliness",
    noise: "Noise",
    sleep: "Sleep",
    study: "Study",
    noBioProvided: "No bio provided yet",
    noInterests: "No interests selected",
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    newRoommateRequest: "New Roommate Request",
    roommateRequestAccepted: "Roommate Request Accepted!",
    roommateRequestDeclined: "Roommate Request Declined",
    compatibility: "Compatibility",
    matchScore: "Match Score",
    viewFullProfile: "View Full Profile",
    roommateDetails: "Roommate Details",
    preferencesMatch: "Preferences Match",
    backToSearch: "Back to Search",
    loadingRoommateProfile: "Loading roommate profile...",
    roommateNotFound: "Roommate not found",
    // Notification specific
    notificationNewMessage: "New Message",
    notificationMatchRequest: "Match Request",
    notificationMatchAccepted: "Match Accepted",
    markAsRead: "Mark as read",
    allNotifications: "All Notifications",
    unreadNotifications: "Unread",
    noUnreadNotifications: "No unread notifications",
    notificationsLoading: "Loading notifications...",
    messagesLoading: "Loading messages...",
    back: "Back",
    guests: "Guests",
    matchRequestSent: "Match request sent!",
    // Matching Priorities
    matchingPriorities: "Matching Priorities",
    matchingPrioritiesSubtitle: "Customize what matters most to you in a roommate",
    priorityBudget: "Budget",
    priorityCleanliness: "Cleanliness",
    priorityNoise: "Noise Level",
    prioritySleepSchedule: "Sleep Schedule",
    priorityStudyHabits: "Study Habits",
    priorityInterests: "Shared Interests",
    priorityMajor: "Same Major",
    prioritySmoking: "Smoking Policy",
    priorityPets: "Pet Policy",
    priorityGuests: "Guest Policy",
    priorityNotImportant: "Not Important",
    prioritySlightlyImportant: "Slightly",
    priorityModerate: "Moderate",
    priorityImportant: "Important",
    priorityVeryImportant: "Very Important",
    // Inactive Profile Warning
    profileInactiveWarning: "Your profile is inactive",
    profileInactiveHint: "Activate your profile to search for and connect with roommates",
    activateProfile: "Activate Profile",
    // Cost Calculator
    smartCostCalculator: "Smart Cost Calculator",
    planYourBudget: "Plan your budget",
    rentAndContract: "Rent & Contract",
    monthlyRent: "Monthly Rent",
    advanceRent: "Advance Rent",
    advanceRentTooltip: "Months of rent to pay upfront.",
    monthShort: "mo",
    roommatesExcludingYou: "Roommates (excluding you)",
    utilitiesMonthly: "Utilities (Monthly)",
    splitWith: "Split with",
    electricity: "Electricity",
    water: "Water",
    internet: "Internet",
    movingAndEssentials: "Moving & Essentials",
    transport: "Transport",
    movingTruck: "Moving Truck",
    essentials: "Essentials",
    bedding: "Bedding",
    internetSetup: "Internet Setup",
    emergencyBuffer: "Emergency Buffer (10%)",
    totalMoveIn: "Total Move-In",
    upfrontRent: "Upfront Rent",
    deposit: "Deposit",
    monthly: "Monthly",
    sameMajor: "Same Major",
    // Verification System
    identityVerification: "Identity Verification",
    verifyIdentityDescription: "Verify your identity to get the Verified Badge and build trust with students",
    verified: "Verified",
    verificationPending: "Verification Pending",
    verificationPendingDescription: "We have received your documents and are reviewing them. This usually takes 1-2 business days.",
    verificationRejected: "Verification Rejected",
    verificationRejectedDescription: "Your previous request was rejected. Please review the requirements and try again.",
    reason: "Reason",
    submitDocuments: "Submit Documents",
    documentType: "Document Type",
    nationalIdCard: "National ID Card",
    passport: "Passport",
    driversLicense: "Driver's License",
    businessLicense: "Business License",
    uploadDocument: "Upload Document",
    clickToUpload: "Click to upload",
    selectFile: "Select File",
    uploading: "Uploading...",
    uploadToCloud: "Upload to Cloud",
    documentUploaded: "Document uploaded successfully",
    submitting: "Submitting...",
    submitForVerification: "Submit for Verification",
    success: "Success",
    verificationSubmitted: "Your verification request has been submitted successfully",
    pending: "Pending Review",
    rejected: "Rejected",
    getVerifiedDescription: "Verify your identity to build trust with students and get the verified badge on your listings",
    reapply: "Reapply",
    viewStatus: "View Status",
    getVerified: "Get Verified",
    verification: "Verification",
    backToProfile: "Back to Profile",
    submitted: "Submitted",
    // Admin Verification Page
    adminVerificationManagement: "Identity Verification Management",
    adminVerificationSubtitle: "Review and manage landlord identity verification requests",
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    noVerificationRequestsFound: "No {status} verification requests found",
    documentTypeLabel: "Document Type",
    submittedOn: "Submitted",
    viewDocument: "View Document",
    reviewNotesLabel: "Review Notes",
    approve: "Approve",
    approveVerification: "Approve Verification Request",
    rejectVerification: "Reject Verification Request",
    confirmApproveMessage: "Are you sure you want to approve the verification request from",
    confirmRejectMessage: "Are you sure you want to reject the verification request from",
    reviewNotesOptional: "Review Notes (Optional)",
    reviewNotesPlaceholder: "Add notes about this decision...",
    processing: "Processing...",
    verificationApprovedSuccess: "Verification request approved successfully",
    verificationRejectedSuccess: "Verification request rejected",
    failedToReviewRequest: "Failed to process request",
    failedToLoadVerificationRequests: "Failed to load verification requests",
    ok: "OK",
    // Admin Announcements
    systemAnnouncements: "System Announcements",
    sendAnnouncementsDescription: "Send system-wide announcements to users",
    announcementTitle: "Enter announcement title",
    announcementMessage: "Enter your announcement message",
    targetAudience: "Target Audience",
    allUsers: "All Users",
    sendToEveryone: "Send to everyone",
    byRole: "By Role",
    targetSpecificRole: "Target specific role",
    byUniversity: "By University",
    targetUniversity: "Target university",
    selectRole: "Select Role",
    students: "Students",
    landlords: "Landlords",
    admins: "Admins",
    pleaseSelectTarget: "Please select a target for this announcement",
    announcementSent: "Announcement sent successfully to",
    failedToSendAnnouncement: "Failed to send announcement",
    sendAnnouncement: "Send Announcement",
    announcements: "Announcements",
    // Community (formerly Forum)
    community: "Community",
    communityDescription: "Connect with students, share experiences, and get advice",
    forum: "Forum",
    forumDescription: "Connect with the community, share experiences, and get advice",
    createPost: "Create Post",
    searchCommunity: "Search community...",
    searchForum: "Search forum...",
    sortBy: "Sort by",
    newest: "Newest",
    mostViewed: "Most Viewed",
    popular: "Popular",
    categories: "Categories",
    all: "All",
    general: "General",
    housing: "Housing",
    tips: "Tips",
    questions: "Questions",
    noPostsFound: "No posts found",
    myPosts: "My Posts",
    noMyPostsYet: "You haven't posted anything yet",
    createYourFirstPost: "Create your first post",
    createFirstPost: "Be the first to post!",
    pinned: "Pinned",
    locked: "Locked",
    upvote: "Upvote",
    downvote: "Downvote",
    views: "views",
    comments: "comments",
    backToCommunity: "Back to Community",
    minsAgo: "m ago",
    hoursAgo: "h ago",
    daysAgo: "d ago",
    justNow: "Just now",
    backToForum: "Back to Forum",
    postNotFound: "Post not found",
    editPost: "Edit Post",
    post: "Post",
    posting: "Posting...",
    postComment: "Post Comment",
    noCommentsYet: "No comments yet",
    addComment: "Write a comment...",
    confirmDeletePost: "Are you sure you want to delete this post?",
    confirmDeleteComment: "Are you sure you want to delete this comment?",
    pin: "Pin",
    unpin: "Unpin",
    lock: "Lock",
    unlock: "Unlock",
    postIsLocked: "This post is locked and cannot be commented on.",
    titleAndContentRequired: "Title and content are required",
    failedToCreatePost: "Failed to create post",
    enterPostTitle: "Enter a catchy title...",
    enterPostContent: "Share your thoughts, questions, or experiences...",
    // Reviews
    reviews: "Reviews",
    writeReview: "Write Review",
    review: "review",
    rating: "Rating",
    ratingDistribution: "Rating Distribution",
    beTheFirst: "Be the first to review!",
    noReviewsYet: "No reviews yet",
    pleaseSelectRating: "Please select a rating",
    commentRequired: "Review comment is required",
    failedToSubmitReview: "Failed to submit review",
    submitReview: "Submit Review",
    editReview: "Edit Review",
    reviewTitlePlaceholder: "Summarize your experience...",
    reviewCommentPlaceholder: "Share details about your experience...",
    prosPlaceholder: "What did you like?",
    consPlaceholder: "What could be improved?",
    yourReview: "Your Review",
    confirmDeleteReview: "Are you sure you want to delete this review?",
    optional: "Optional",
    helpful: "Helpful",
    deletePost: "Delete Post",
    deleteComment: "Delete Comment",
    deleteReview: "Delete Review",
    pros: "Pros",
    cons: "Cons",
    // Marketplace
    studentMarketplace: "Student Marketplace",
    marketplaceDescription: "Buy and sell items with fellow students",
    searchMarketplace: "Search items...",
    latestItems: "Latest Items",
    myItems: "My Items",
    postItem: "Post Item",
    noItemsFound: "No items found",
    noMyItemsYet: "You haven't posted any items yet",
    postYourFirstItem: "Post your first item for sale",
    deleteItemConfirm: "Are you sure you want to delete this item? This action cannot be undone.",
    items: "items",
    failedToLoadItems: "Failed to load items",
    failedToCreateItem: "Failed to post item",
    itemCreatedSuccessfully: "Item posted successfully!",
    itemUpdatedSuccessfully: "Item updated successfully!",
    editItem: "Edit Item",
    pleaseSignInToPostItem: "Please sign in to post items for sale.",
    pleaseSignInToViewMarketplace: "Please sign in to view the marketplace.",
    accessRestricted: "Access Restricted",
    marketplaceLandlordRestricted: "The marketplace is only available for students. As a landlord, you can manage your properties in the Apartments section.",
    goToApartments: "Go to Apartments",
    // Categories
    category: "Category",
    categoryFurniture: "Furniture",
    categoryElectronics: "Electronics",
    categoryBooks: "Books",
    categoryClothing: "Clothing",
    categoryKitchenware: "Kitchenware",
    categorySports: "Sports",
    categoryOther: "Other",
    // Conditions
    condition: "Condition",
    conditionNew: "New",
    conditionLikeNew: "Like New",
    conditionGood: "Good",
    conditionFair: "Fair",
    // Item form
    itemTitlePlaceholder: "What are you selling?",
    itemDescriptionPlaceholder: "Describe your item...",
    contactPhone: "Contact Phone",
    contactEmail: "Contact Email",
    remaining: "remaining",
    // Item details
    sellerInfo: "Seller Information",
    itemNotFound: "Item not found",
    failedToLoadItem: "Failed to load item",
    // Landlord Features - Viewings
    landlordDashboard: "Landlord Dashboard",
    manageAvailability: "Manage Availability",
    availability: "Availability",
    upcomingViewings: "Upcoming Viewings",
    scheduleViewing: "Schedule Viewing",
    viewingDate: "Viewing Date",
    viewingTime: "Viewing Time",
    viewingStatus: "Status",
    viewingNotes: "Notes",
    confirmViewing: "Confirm",
    cancelViewing: "Cancel Viewing",
    noViewingsScheduled: "No viewings scheduled",
    viewingConfirmed: "Viewing confirmed",
    viewingCancelled: "Viewing cancelled",
    viewingPending: "Pending",
    viewingCompleted: "Completed",
    viewingNoShow: "No Show",
    bookViewing: "Book Viewing",
    selectDate: "Select Date",
    selectTime: "Select Time",
    studentNotes: "Your Notes",
    studentNotesPlaceholder: "Any questions or special requests?",
    viewingBooked: "Viewing booked successfully!",
    viewingRequestSent: "Viewing request sent to landlord",
    failedToBookViewing: "Failed to book viewing",
    setAvailability: "Set Availability",
    weeklyAvailability: "Weekly Availability",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    startTime: "Start Time",
    endTime: "End Time",
    addTimeSlot: "Add Time Slot",
    availabilityUpdated: "Availability updated successfully",
    noAvailability: "No availability set",
    failedToLoadAvailability: "Failed to load availability",
    // Landlord Features - Analytics
    analytics: "Analytics",
    totalViews: "Total Views",
    totalFavorites: "Total Favorites",
    totalInquiries: "Total Inquiries",
    propertiesCount: "Active Properties",
    performanceTrends: "Performance Trends",
    propertyPerformance: "Property Performance",
    last30Days: "Last 30 Days",
    viewsOverTime: "Views Over Time",
    favoritesOverTime: "Favorites Over Time",
    inquiriesOverTime: "Inquiries Over Time",
    noAnalyticsData: "No analytics data available",
    failedToLoadAnalytics: "Failed to load analytics",
    propertyAnalytics: "Property Analytics",
    dailyStats: "Daily Statistics",
    engagementRate: "Engagement Rate",
    conversionRate: "Conversion Rate",
    // Landlord Features - Price History
    priceHistory: "Price History",
    priceChanges: "Price Changes",
    currentPrice: "Current Price",
    previousPrice: "Previous Price",
    priceIncrease: "Price Increase",
    priceDecrease: "Price Decrease",
    priceChange: "Price Change",
    changePercentage: "Change",
    recordedAt: "Date",
    initialPrice: "Initial Price",
    noPriceHistory: "No price changes recorded",
    failedToLoadPriceHistory: "Failed to load price history",
    // Landlord Features - Market Insights
    marketInsights: "Market Insights",
    averagePrice: "Average Price",
    marketTrends: "Market Trends",
    priceComparison: "Price Comparison",
    byPropertyType: "By Property Type",
    nearUniversity: "Near University",
    marketAverage: "Market Average",
    yourPrice: "Your Price",
    competitive: "Competitive",
    aboveMarket: "Above Market",
    belowMarket: "Below Market",
    // Common
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    yesterday: "Yesterday",
    dateRange: "Date Range",
    noDataAvailable: "No data available",
    // New pages - Price History & Reviews
    viewPriceHistory: "View Price History",
    trackPriceChanges: "Track your property price changes over time",
    seeAllReviews: "See All Reviews",
    allReviews: "All Reviews",
    averageRating: "Average Rating",
    totalChange: "Total Change",
    foundHelpful: "people found this helpful",
    goBack: "Go Back",
    unauthorized: "You are not authorized to view this page",
    prices: "Prices",
    viewingBookedSuccess: "Viewing booked successfully! The landlord will be notified.",
    // Distance Filter
    allUniversities: "All Universities",
    distanceFromUniversity: "Distance from University",
    propertyVideo: "Property Video",
    distanceAway: "away",
    // Nearby Places
    nearbyPlaces: "Nearby Places",
    showOnMap: "Show on map",
    propertiesOnMap: "properties on map",
    supermarket: "Supermarkets",
    restaurant: "Restaurants",
    pharmacy: "Pharmacies",
    bank: "Banks",
    bus_station: "Bus Stations",
    cafe: "Cafes",
    distance200m: "200m",
    distance500m: "500m",
    distance1km: "1 km",
    distance2km: "2 km",
    distance5km: "5 km",
    distanceHint: "Show properties within this radius",
    selectUniversityForDistance: "Select a university first to filter by distance",
    // Reports
    reportsManagement: "Reports Management",
    reportsManagementSubtitle: "Review and manage user reports",
    reportUser: "Report User",
    reportReasonSpam: "Spam",
    reportReasonHarassment: "Harassment",
    reportReasonInappropriate: "Inappropriate Content",
    reportReasonScam: "Scam or Fraud",
    reportReasonHateSpeech: "Hate Speech",
    reportReasonThreats: "Threats",
    reportReasonOther: "Other",
    selectReportReason: "Please select a reason",
    reportFailed: "Failed to submit report",
    reportSubmitted: "Report submitted successfully",
    reportReviewMessage: "Our team will review this report",
    reportDescription: "Report for inappropriate behavior",
    additionalDetails: "Additional Details",
    reportDetailsPlaceholder: "Provide any additional context...",
    submitReport: "Submit Report",
    failedToLoadReports: "Failed to load reports",
    failedToLoadReportDetails: "Failed to load report details",
    noReportsFound: "No reports found",
    reportStatusPending: "Pending",
    reportStatusReviewed: "Reviewed",
    reportStatusResolved: "Resolved",
    reportStatusDismissed: "Dismissed",
    reportActionNone: "No Action",
    reportActionWarning: "Warning",
    reportActionSuspended: "Suspended",
    reportActionBanned: "Banned",
    reportedBy: "Reported by",
    reportedUser: "Reported user",
    reportedMessage: "Reported Message",
    adminNotes: "Admin Notes",
    adminNotesPlaceholder: "Add internal notes about this decision...",
    reportDetails: "Report Details",
    reportInfo: "Report Information",
    conversationHistory: "Conversation History",
    dismissReport: "Dismiss Report",
    sendWarningTitle: "Send Warning",
    suspendUserTitle: "Suspend User",
    banUserTitle: "Ban User",
    confirmDismissReport: "Are you sure you want to dismiss this report?",
    confirmSendWarning: "Send a warning to",
    confirmSuspendUser: "Suspend messaging for",
    confirmBanUser: "Ban user",
    warningMessage: "Warning Message",
    warningMessagePlaceholder: "Enter warning message to send to user...",
    sendWarning: "Send Warning",
    suspendUser: "Suspend",
    banUser: "Ban",
    reportActionSuccess: "Report action completed successfully",
    failedToProcessReport: "Failed to process report",
    userUnsuspended: "User messaging unsuspended successfully",
    failedToUnsuspendUser: "Failed to unsuspend user",
    close: "Close",
    error: "Error",
    // AI Chat
    aiChatNewChat: "New chat",
    aiChatNoConversationsYet: "No conversations yet",
    aiChatStartChatting: "Start chatting to create one!",
    aiChatRecentChats: "Recent Chats",
    aiChatDeleteConversation: "Delete conversation",
    aiChatDeleteConversationTitle: "Delete Conversation?",
    aiChatDeleteConversationMessage: "Are you sure you want to delete this conversation? This action cannot be undone.",
    aiChatUniNestAssistant: "UniNest Assistant",
    aiChatPropertyExpert: "Property Expert",
    aiChatYourCaringAssistant: "Your caring assistant",
    aiChatPropertyMarketingExpert: "Property marketing expert",
    aiChatWhatCanIHelp: "What can I help with?",
    aiChatHowCanIHelpProperty: "How can I help your property?",
    aiChatStudentDescription: "Ask me about cooking, cleaning, budgeting, or any student life tips!",
    aiChatLandlordDescription: "Get expert advice on marketing, pricing, and tenant management.",
    aiChatAskMeAnything: "Ask me anything...",
    aiChatHowCanIHelpPropertyInput: "How can I help with your property?",
    aiChatCanMakeMistakes: "can make mistakes. Consider checking important info.",
    aiChatNewConversation: "New conversation",
    aiChatJustNow: "Just now",
    aiChatMinutesAgo: "m ago",
    aiChatHoursAgo: "h ago",
    aiChatDaysAgo: "d ago",
    aiChatMessages: "msg",
    // Admin Dashboard
    adminDashboard: "Admin Dashboard",
    platformOverview: "Platform overview and management",
    totalUsers: "Total Users",
    totalProperties: "Total Properties",
    pendingReports: "Pending Reports",
    pendingVerifications: "Pending Verifications",
    newThisMonth: "New this month",
    totalReports: "Total reports",
    approved: "Approved",
    userRegistrations: "User Registrations (30 Days)",
    userDistribution: "User Distribution",
    newProperties: "New Properties (30 Days)",
    forumActivity: "Forum Activity (30 Days)",
    propertyViewings: "Property Viewings",
    roommateProfiles: "Roommate Profiles",
    recentReports: "Recent Reports",
    recentVerifications: "Recent Verifications",
    viewAll: "View All",
    noRecentReports: "No recent reports",
    noRecentVerifications: "No recent verifications",
    quickActions: "Quick Actions",
    manageUsers: "Manage Users",
    viewAndManageUsers: "View and manage all platform users",
    reviewReports: "Review Reports",
    handleReportsModeration: "Handle user reports and moderation",
    verifications: "Verifications",
    approveRejectRequests: "Approve or reject verification requests",
    manageUniversities: "Manage Universities",
    manageUniversityListings: "Manage university listings",
    createManageAnnouncements: "Create and manage announcements",
    manageAdminUsersSuper: "Manage admin users (SuperAdmin only)",
    // Admin Users Management
    userManagement: "User Management",
    viewManageAllUsers: "View and manage all platform users",
    searchByNameEmail: "Search by name or email...",
    allRoles: "All Roles",
    superAdmins: "Super Admins",
    user: "User",
    status: "Status",
    joined: "Joined",
    notVerified: "Not Verified",
    showingUsers: "Showing {count} of {total} users",
    previous: "Previous",
    next: "Next",
    noUsersFound: "No users found",
    forumPosts: "Forum Posts",
  },
  ar: {
    apartments: "الشقق",
    marketplace: "السوق",
    about: "حول",
    contact: "اتصل",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    welcomeBack: "مرحباً بعودتك! سجّل الدخول للمتابعة",
    createYourAccount: "أنشئ حسابك للبدء",
    heroTitle:
      "ابحث عن مكانك المثالي بالقرب من الحرم الجامعي — آمن ومُوثق وصديق للطلاب.",
    heroSubtitle: "بسّط بحثك عن السكن مع قوائم موثقة وملّاك موثوقين",
    startSearching: "ابدأ البحث",
    verifiedRentals: "إيجارات موثقة",
    campusHousing: "سكن جامعي",
    affordableHousing: "سكن طلابي بأسعار معقولة",
    aboutUs: "من نحن",
    aboutUsText:
      "مرحباً بك في UniNest — مركز السكن الطلابي الموثوق. نربط طلاب الجامعة بسكن آمن ومُوثق بالقرب من الحرم الجامعي. استكشف المطابقة الشخصية والفلاتر التي تناسب ميزانيتك وأسلوب حياتك. ابدأ فصلك التالي بثقة.",
    ourOffers: "عروضنا",
    readyTitle: "هل أنت مستعد لإيجاد منزلك القادم؟",
    builtForStudents: "مبني للطلاب من قبل الطلاب",
    weUnderstand: "نحن نفهم ما تحتاجه حياة الحرم الجامعي",
    home: "الرئيسية",
    aboutUsLink: "من نحن",
    connect: "تواصل",
    rightsReserved: "©2025 جميع الحقوق محفوظة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    phoneNumber: "رقم الهاتف",
    student: "طالب",
    landlord: "صاحب عقار",
    admin: "مشرف",
    superadmin: "مشرف عام",
    studentId: "الرقم الجامعي",
    university: "الجامعة",
    selectUniversity: "اختر جامعتك",
    forgotPassword: "هل نسيت كلمة المرور؟",
    sendResetCode: "إرسال رمز إعادة التعيين",
    resetLinkSent:
      "إذا كان هذا البريد موجودًا، فقد تم إرسال رمز إعادة التعيين.",
    noAccount: "ليس لديك حساب؟",
    createOne: "إنشاء واحد",
    passwordAgain: "كلمة المرور مرة أخرى",
    haveAccount: "هل لديك حساب؟",
    logIn: "تسجيل الدخول",
    marketplaceTitle: "السوق",
    marketplaceSubtitle: "حياة الطلاب أصبحت بسيطة: ابحث، تحقق، انتقل.",
    searchPlaceholder: "ابحث هنا",
    lastListings: "آخر الإعلانات",
    offers: "العروض",
    favorites: "المفضلة",
    masonry: "البناء",
    postAd: "انشر إعلان",
    filters: "الفلاتر",
    price: "السعر",
    squareMeter: "متر مربع",
    availableIn: "متاح في",
    garage: "جراج",
    yes: "نعم",
    no: "لا",
    rooms: "الغرف",
    partner: "شريك",
    ownerOfProperty: "مالك العقار",
    messageNow: "راسل الآن",
    beds: "سرير",
    baths: "حمام",
    kitchen: "مطبخ",
    livingRoom: "صالة",
    overview: "نظرة عامة",
    startingFrom: "يبدأ من",
    myProfile: "ملفي الشخصي",
    logout: "تسجيل الخروج",
    signInRequired: "يتطلب تسجيل الدخول",
    logInRequired: "يتطلب تسجيل الدخول",
    pleaseSignInToMessage: "يرجى تسجيل الدخول لمراسلة مالك العقار.",
    pleaseSignInToAddFavorite: "يرجى تسجيل الدخول لإضافة العقارات إلى قائمة المفضلة.",
    pleaseSignInToViewFavorites: "يرجى تسجيل الدخول لعرض المفضلة.",
    pleaseSignInToPostAd: "يرجى تسجيل الدخول لنشر إعلان والتواصل مع الطلاب.",
    signingIn: "جارٍ تسجيل الدخول...",
    creatingAccount: "جارٍ إنشاء الحساب...",
    createAdComingSoon: "ميزة إنشاء الإعلان ستتوفر قريبًا!",
    propertyNotFound: "العقار غير موجود",
    backToMarketplace: "العودة إلى السوق",
    loadingApartments: "جارٍ تحميل الشقق...",
    loadingProperty: "جارٍ تحميل العقار...",
    // Admin Dashboard
    adminDashboard: "لوحة تحكم المشرف",
    platformOverview: "نظرة عامة على المنصة والإدارة",
    totalUsers: "إجمالي المستخدمين",
    totalProperties: "إجمالي العقارات",
    pendingReports: "التقارير المعلقة",
    pendingVerifications: "التحققات المعلقة",
    newThisMonth: "جديد هذا الشهر",
    totalReports: "إجمالي التقارير",
    approved: "موافق عليه",
    userRegistrations: "تسجيلات المستخدمين (30 يوم)",
    userDistribution: "توزيع المستخدمين",
    newProperties: "عقارات جديدة (30 يوم)",
    forumActivity: "نشاط المنتدى (30 يوم)",
    propertyViewings: "معاينات العقارات",
    roommateProfiles: "ملفات الزملاء",
    recentReports: "التقارير الأخيرة",
    recentVerifications: "التحققات الأخيرة",
    viewAll: "عرض الكل",
    noRecentReports: "لا توجد تقارير حديثة",
    noRecentVerifications: "لا توجد تحققات حديثة",
    quickActions: "إجراءات سريعة",
    manageUsers: "إدارة المستخدمين",
    viewAndManageUsers: "عرض وإدارة جميع مستخدمي المنصة",
    reviewReports: "مراجعة التقارير",
    handleReportsModeration: "التعامل مع تقارير المستخدمين والإشراف",
    verifications: "التحققات",
    approveRejectRequests: "الموافقة أو رفض طلبات التحقق",
    manageUniversities: "إدارة الجامعات",
    manageUniversityListings: "إدارة قوائم الجامعات",
    createManageAnnouncements: "إنشاء وإدارة الإعلانات",
    manageAdminUsersSuper: "إدارة المشرفين (المشرف العام فقط)",
    // Admin Users Management
    userManagement: "إدارة المستخدمين",
    viewManageAllUsers: "عرض وإدارة جميع مستخدمي المنصة",
    searchByNameEmail: "البحث بالاسم أو البريد الإلكتروني...",
    allRoles: "جميع الأدوار",
    superAdmins: "المشرفون العامون",
    user: "المستخدم",
    status: "الحالة",
    joined: "انضم",
    notVerified: "غير موثق",
    showingUsers: "عرض {count} من {total} مستخدم",
    previous: "السابق",
    next: "التالي",
    noUsersFound: "لم يتم العثور على مستخدمين",
    forumPosts: "منشورات المنتدى",
    loadingMarketplace: "جارٍ تحميل السوق...",
    loadingMessages: "جارٍ تحميل الرسائل...",
    loadingUniversities: "جارٍ تحميل الجامعات...",
    profile: "الملف الشخصي",
    loadingProfile: "جارٍ تحميل الملف الشخصي...",
    failedToLoadProfile: "فشل في تحميل الملف الشخصي",
    goHome: "العودة للرئيسية",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
    contactInformation: "معلومات التواصل",
    personalInformation: "المعلومات الشخصية",
    studentInformation: "معلومات الطالب",
    profilePicture: "صورة الملف الشخصي",
    firstNameRequired: "الاسم الأول مطلوب",
    lastNameRequired: "اسم العائلة مطلوب",
    invalidPhone: "صيغة رقم الهاتف غير صحيحة",
    gender: "الجنس",
    editProfile: "تعديل الملف",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    selectGender: "اختر الجنس",
    genderMale: "ذكر",
    genderFemale: "أنثى",
    preferredLanguageLabel: "اللغة المفضلة",
    languageEnglish: "الإنجليزية",
    languageFrench: "الفرنسية",
    languageArabic: "العربية",
    avatarUrlLabel: "رابط الصورة الشخصية",
    avatarUrlPlaceholder: "https://example.com/avatar.jpg",
    preview: "معاينة:",
    phonePlaceholder: "مثال: +1 (555) 123-4567",
    enterFirstName: "أدخل الاسم الأول",
    enterLastName: "أدخل اسم العائلة",
    studentIdLabel: "الرقم الجامعي",
    studentIdPlaceholder: "أدخل رقمك الجامعي",
    notProvided: "غير متوفر",
    notSpecified: "غير محدد",
    notAssigned: "غير معين",
    ratings: "التقييمات",
    averageRating: "متوسط التقييم",
    totalReviews: "إجمالي المراجعات",
    accountCreated: "تم إنشاء الحساب",
    lastUpdated: "آخر تحديث",
    deleteAccount: "حذف الحساب",
    deleteAccountWarning:
      "سيتم حذف حسابك وجميع البيانات المرتبطة به نهائيًا. لا يمكن التراجع عن هذا الإجراء.",
    delete: "حذف",
    deleteAccountBullet1: "يزيل المحادثات والمفضلة والقوائم.",
    deleteAccountBullet2: "سيتم تسجيل خروجك على الفور.",
    Delete: "حذف",
    // Alert Modals
    deleteProfilePictureTitle: "حذف الصورة الشخصية",
    deleteProfilePictureMessage: "سيتم إزالة صورتك الحالية. لن يتم تطبيق التغيير إلا بعد النقر على حفظ التغييرات.",
    confirm: "تأكيد",
    // Admin Page
    addUniversity: "إضافة جامعة",
    editUniversity: "تعديل الجامعة",
    universityName: "اسم الجامعة",
    city: "المدينة",
    domain: "النطاق",
    latitude: "خط العرض",
    longitude: "خط الطول",
    deleteUniversity: "حذف الجامعة",
    deleteUniversityMessage: "لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد أنك تريد حذف هذه الجامعة؟",
    saving: "جارٍ الحفظ...",
    adding: "جارٍ الإضافة...",
    save: "حفظ",
    add: "إضافة",
    verified: "موثّق",
    updateDetails: "يرجى تحديث البيانات أدناه",
    fillDetails: "يرجى تعبئة البيانات أدناه",
    // Auth Alerts
    accountCreatedTitle: "تم إنشاء الحساب!",
    accountCreatedMessage: "تم إنشاء حسابك بنجاح. يرجى تسجيل الدخول للمتابعة.",
    signInNow: "سجل الدخول الآن",
    ctaBrowseSubtitle:
      "تصفح مئات الشقق الموثوقة والصديقة للطلاب وابحث عن منزلك المثالي اليوم",
    // About Page
    ourMission: "مهمتنا",
    missionParagraph:
      "نوجد لإزالة التعقيد من سكن الطلاب. لا مزيد من منشورات وسائل التواصل التي لا تنتهي أو سلاسل الملاك غير الموثوقة. تقوم UniNest بدمج القوائم الموثوقة، والأسعار الشفافة والتواصل البسيط — حتى تركز على دراستك وحياتك الجامعية.",
    missionPoint1: "قوائم موثقة وشفافية في التسعير.",
    missionPoint2: "أدوات تطابق نمط الحياة (هادئ، اجتماعي، مناسب للشريك).",
    missionPoint3: "دعم للطلاب الدوليين وطلاب السنة الأولى.",
    missionPoint4: "نهج شامل للاحتياجات المالية وإمكانية الوصول.",
    coreValues: "القيم الأساسية",
    howItWorks: "كيف تعمل المنصة",
    startExploring: "ابدأ الاستكشاف",
    hiwDiscoverTitle: "اكتشف",
    hiwDiscoverDesc: "تصفح قوائم موثقة وملائمة للطلاب بالقرب من الجامعة.",
    hiwCompareTitle: "قارن",
    hiwCompareDesc:
      "صفِّ حسب الميزانية، والمسافة، والمرافق، وخيارات السكن المشترك.",
    hiwConnectTitle: "تواصل",
    hiwConnectDesc: "راسل الملاك بأمان وحدد مواعيد الزيارات بسرعة.",
    hiwMoveInTitle: "انتقل",
    hiwMoveInDesc: "ابدأ فصلك الدراسي مستقرًا وواثقًا ومستعدًا.",
    // Contact Page
    contactSubtitle: "يسعدنا سماعك — أسئلة أو اقتراحات أو أفكار شراكة.",
    sendMessageHeading: "أرسل رسالة",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    messageLabel: "الرسالة",
    namePlaceholder: "اسمك",
    emailPlaceholder: "you@example.com",
    messagePlaceholder: "أخبرنا كيف يمكننا مساعدتك...",
    sendMessage: "إرسال الرسالة",
    sent: "تم الإرسال!",
    privacyNotice:
      "نرد خلال 24 ساعة (أيام الأسبوع). تُستخدم بياناتك فقط للرد على هذا الطلب.",
    orEmailDirectly: "أو راسلنا مباشرة",
    contactInfo: "معلومات التواصل",
    supportLabel: "الدعم",
    responseTimeLabel: "زمن الاستجابة",
    supportHours: "الأحد - الخميس",
    usualResponse: "عادة نرد خلال 24 ساعة.",
    faqs: "الأسئلة الشائعة",
    faqQ1: "كيف يتم توثيق القوائم؟",
    faqA1: "نراجع يدويًا مستندات الملكية ونجري فحوصات الاتساق قبل النشر.",
    faqQ2: "هل يمكنني تحديد موعد زيارة؟",
    faqA2: "نعم. استخدم ميزة الرسائل في القائمة لطلب أوقات الزيارة مباشرة.",
    faqQ3: "هل تدعمون مطابقة زملاء السكن؟",
    faqA3: "نُطلق قريبًا نسخة تجريبية للمطابقة — ترقب!",
    messageSentSuccess: "تم إرسال الرسالة بنجاح!",
    // About Feature Descriptions
    aboutDesc1: "الثقة والأمان أولاً في كل قائمة نتحقق منها.",
    aboutDesc2: "مصمم لحياة الطالب: قرب، مجتمع، توازن.",
    aboutDesc3: "نهتم بالقدرة المالية — خيارات لميزانيات مختلفة.",
    // Forgot Password
    forgotPasswordInstructions: "أدخل عنوان بريدك الإلكتروني وسنرسل لك رمزًا لإعادة تعيين كلمة المرور.",
    rememberPassword: "هل تتذكر كلمة المرور؟",
    backToSignIn: "العودة لتسجيل الدخول",
    // Header
    theme: "المظهر",
    language: "اللغة",
    dark: "داكن",
    light: "فاتح",
    english: "الإنجليزية",
    arabic: "العربية",
    notifications: "الإشعارات",
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات بعد.",
    messages: "الرسائل",
    noConversations: "لا توجد محادثات بعد.",
    conversation: "محادثة",
    noMessagesYet: "لا توجد رسائل بعد",
    messageOptions: "خيارات الرسالة",
    deleteMessage: "حذف الرسالة",
    deleteMessageConfirm: "هل أنت متأكد من حذف هذه الرسالة؟ لا يمكن التراجع عن هذا الإجراء.",
    messageDeleted: "تم حذف الرسالة",
    loading: "جارٍ التحميل...",
    // Profile Page
    uploadPicture: "رفع صورة",
    dangerZone: "منطقة الخطر",
    administration: "الإدارة",
    universities: "الجامعات",
    adminManagement: "إدارة المشرفين",
    manageAdminUsers: "إدارة المشرفين والصلاحيات",
    createAdmin: "إنشاء مشرف",
    adminUsers: "المشرفون",
    noAdminsFound: "لم يتم العثور على مشرفين",
    fillAdminDetails: "أدخل بيانات المشرف",
    creating: "جارٍ الإنشاء...",
    create: "إنشاء",
    deleteAdmin: "حذف المشرف",
    deleteAdminMessage: "هل أنت متأكد من حذف هذا المشرف؟ لا يمكن التراجع عن هذا الإجراء.",
    name: "الاسم",
    role: "الدور",
    createdAt: "تاريخ الإنشاء",
    actions: "الإجراءات",
    accountMenu: "قائمة الحساب",
    guestMenu: "قائمة الضيف",
    // Post Ad Modal
    "Create listing": "إنشاء إعلان",
    "Post a Property Ad": "نشر إعلان عقار",
    "Listing basics": "أساسيات الإعلان",
    "Listing title": "عنوان الإعلان",
    "Cozy 2BR near campus": "شقة مريحة بغرفتين قرب الجامعة",
    Description: "الوصف",
    "Describe the place, amenities, nearby spots": "صف المكان والمرافق والأماكن القريبة",
    "Property type": "نوع العقار",
    "Loading universities...": "جارٍ تحميل الجامعات...",
    "Select a university": "اختر جامعة",
    "Pricing & details": "التسعير والتفاصيل",
    "Monthly price": "السعر الشهري",
    Bedrooms: "غرف النوم",
    Bathrooms: "الحمامات",
    "Size (m^2)": "المساحة (متر مربع)",
    "Distance to university (km)": "المسافة إلى الجامعة (كم)",
    "Lease duration": "مدة الإيجار",
    "e.g. 12 months": "مثال: 12 شهر",
    "Upload images": "رفع الصور",
    "Up to 10 images. Remaining": "حتى 10 صور. المتبقي",
    "Uploading...": "جارٍ الرفع...",
    "Click or drop to upload": "انقر أو اسحب للرفع",
    remove: "إزالة",
    Tip: "نصيحة",
    "Great photos increase engagement": "الصور الجيدة تزيد التفاعل",
    "Posting...": "جارٍ النشر...",
    "Ad created successfully": "تم إنشاء الإعلان بنجاح",
    // Apartments Page - Filters & Listings
    clearAll: "مسح الكل",
    min: "الحد الأدنى",
    max: "الحد الأقصى",
    allCities: "جميع المدن",
    showingResults: "عرض",
    properties: "عقارات",
    tryAgain: "حاول مرة أخرى",
    noListingsFound: "لم يتم العثور على إعلانات",
    tryAdjustingFilters: "حاول تعديل الفلاتر أو البحث",
    clearFilters: "مسح الفلاتر",
    failedToLoadListings: "فشل في تحميل الإعلانات",
    failedToCreateAd: "فشل في إنشاء الإعلان",
    fillRequiredFields: "يرجى ملء جميع الحقول المطلوبة",
    maxImagesError: "الحد الأقصى 10 صور لكل إعلان",
    canAddMoreImages: "يمكنك إضافة",
    moreImages: "صورة إضافية",
    failedToLoadUniversities: "فشل في تحميل الجامعات",
    propertyListing: "إعلان عقار",
    // Map & Location
    location: "الموقع",
    showOnMap: "عرض على الخريطة",
    distance: "المسافة",
    mapView: "خريطة",
    gridView: "شبكة",
    propertyLocation: "موقع العقار",
    searchLocation: "ابحث عن عنوان...",
    selectedLocation: "الموقع المحدد",
    locationPickerHint: "انقر على الخريطة أو ابحث عن عنوان لتحديد موقع العقار",
    propertiesOnMap: "عقارات على الخريطة",
    // Listing Duration
    listingDuration: "مدة الإعلان",
    listingDurationHint: "كم من الوقت سيظل الإعلان مرئياً",
    "1week": "أسبوع واحد",
    "2weeks": "أسبوعان",
    "1month": "شهر واحد",
    "2months": "شهران",
    "3months": "3 أشهر",
    expiresAt: "ينتهي في",
    renewListing: "تجديد الإعلان",
    listingExpired: "الإعلان منتهي",
    listingRenewed: "تم تجديد الإعلان بنجاح",
    month: "شهر",
    Apartment: "شقة",
    House: "منزل",
    Room: "غرفة",
    Studio: "استوديو",
    // Universities Management Page
    universitiesManagement: "إدارة الجامعات",
    manageUniversityInfo: "إدارة معلومات الجامعات والمواقع",
    universityCity: "المدينة",
    universityDomain: "النطاق",
    universityLatitude: "خط العرض",
    universityLongitude: "خط الطول",
    clickRowToEdit: "نصيحة: انقر على أي صف جامعة لفتح خيارات التعديل/الحذف.",
    confirmDeleteUniversity: "هل أنت متأكد من حذف هذه الجامعة؟",
    universityDeleted: "تم حذف الجامعة بنجاح",
    universityUpdated: "تم تحديث الجامعة بنجاح",
    universityCreated: "تم إنشاء الجامعة بنجاح",
    noUniversitiesFound: "لم يتم العثور على جامعات",
    distanceToUniversityMeters: "المسافة إلى الجامعة (بالمتر)",
    autoCalculated: "يتم حسابها تلقائياً من الخريطة",
    // Filters & Post Ad
    applyFilters: "تطبيق الفلاتر",
    maxOccupants: "الحد الأقصى للسكان",
    maxOccupantsHint: "الحد الأقصى لعدد الأشخاص المسموح بهم",
    "Size (m²)": "المساحة (م²)",
    imagesRequired: "مطلوب صورة واحدة على الأقل",
    imageUploadFailed: "فشل في رفع الصور",
    viewAllImages: "عرض جميع الصور",
    images: "صور",
    image: "صورة",
    mark360: "360°",
    "360Image": "بانوراما 360°",
    // My Listings Page
    myListings: "إعلاناتي",
    manageYourProperties: "إدارة إعلانات عقاراتك",
    postNewAd: "نشر إعلان جديد",
    noListingsYet: "لا توجد إعلانات بعد",
    startByCreating: "ابدأ بإنشاء أول إعلان عقار لك",
    createListing: "إنشاء إعلان",
    visible: "مرئي",
    hidden: "مخفي",
    view: "عرض",
    edit: "تعديل",
    hide: "إخفاء",
    show: "إظهار",
    confirmDelete: "تأكيد الحذف",
    deleteListingConfirm: "هل أنت متأكد من حذف هذا الإعلان؟ لا يمكن التراجع عن هذا الإجراء.",
    editListing: "تعديل الإعلان",
    title: "العنوان",
    description: "الوصف",
    pricePerMonth: "السعر/الشهر",
    propertyType: "نوع العقار",
    bedrooms: "غرف النوم",
    bathrooms: "الحمامات",
    size: "المساحة",
    distanceToUniversity: "المسافة إلى الجامعة",
    leaseDuration: "مدة الإيجار",
    dismiss: "إغلاق",
    listingBasics: "أساسيات الإعلان",
    listingTitle: "عنوان الإعلان",
    pricingDetails: "التسعير والتفاصيل",
    monthlyPrice: "السعر الشهري",
    // Password Change
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    sendVerificationCode: "إرسال رمز التحقق",
    verificationCode: "رمز التحقق",
    passwordWillBeEmailed: "سيتم إنشاء كلمة مرور آمنة وإرسالها إلى بريد المشرف",
    passwordChangedSuccessfully: "تم تغيير كلمة المرور بنجاح",
    verificationCodeSent: "تم إرسال رمز التحقق إلى بريدك الإلكتروني",
    enterVerificationCode: "أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك",
    passwordMustMatch: "يجب أن تتطابق كلمات المرور",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    updateYourPassword: "تحديث كلمة مرور حسابك",
    clickToSendCode: "انقر على الزر أدناه لتلقي رمز التحقق عبر البريد الإلكتروني",
    sending: "جارٍ الإرسال...",
    changing: "جارٍ التغيير...",
    // Roommate Matching
    roommates: "زملاء السكن",
    findRoommates: "ابحث عن زملاء سكن",
    roommateProfile: "ملف زميل السكن",
    roommateProfileSubtitle: "حدد تفضيلاتك للعثور على زملاء سكن متوافقين",
    findRoommatesSubtitle: "تواصل مع طلاب متوافقين يبحثون عن زملاء سكن",
    loadingRoommates: "جارٍ تحميل زملاء السكن...",
    budgetPreferences: "تفضيلات الميزانية",
    minBudget: "الحد الأدنى للميزانية",
    maxBudget: "الحد الأقصى للميزانية",
    livingPreferences: "تفضيلات السكن",
    cleanlinessLevel: "مستوى النظافة",
    noiseLevel: "مستوى الضوضاء",
    sleepSchedule: "جدول النوم",
    studyHabits: "عادات الدراسة",
    lifestyle: "نمط الحياة",
    smokingAllowed: "التدخين مسموح",
    petsAllowed: "الحيوانات مسموحة",
    guestsPolicy: "سياسة الضيوف",
    aboutYou: "عنك",
    moveInDate: "تاريخ الانتقال",
    bio: "نبذة",
    bioPlaceholder: "أخبر زملاء السكن المحتملين عن نفسك واهتماماتك وما تبحث عنه...",
    profileActive: "الملف نشط",
    profileInactive: "الملف غير نشط",
    profileSaved: "تم حفظ الملف بنجاح!",
    profileDeactivated: "تم تعطيل الملف",
    saveProfile: "حفظ الملف",
    manageMatches: "إدارة المطابقات",
    removeMatch: "إزالة",
    removeMatchConfirm: "هل أنت متأكد أنك تريد إزالة هذه المطابقة؟",
    matchRemoved: "تمت إزالة المطابقة بنجاح!",
    relaxed: "مرن",
    veryClean: "نظيف جداً",
    quiet: "هادئ",
    social: "اجتماعي",
    sleepEarly: "مبكر النوم",
    sleepNormal: "عادي",
    sleepLate: "سهران",
    studyHome: "في المنزل",
    studyLibrary: "المكتبة",
    studyMixed: "مختلط",
    guestsNever: "أبداً",
    guestsSometimes: "أحياناً",
    guestsOften: "كثيراً",
    smokingOk: "التدخين مسموح",
    noSmoking: "ممنوع التدخين",
    petsOk: "الحيوانات مسموحة",
    noPets: "ممنوع الحيوانات",
    cleanlinessRelaxed: "مرن",
    cleanlinessFlexible: "مرن",
    cleanlinessModerate: "معتدل",
    cleanlinessClean: "نظيف",
    cleanlinessVeryClean: "نظيف جداً",
    upTo: "حتى",
    connectRoommate: "تواصل",
    connecting: "جارٍ الاتصال...",
    search: "بحث",
    matches: "التطابقات",
    roommatesFound: "زملاء سكن وجدوا",
    noRoommatesFound: "لم يتم العثور على زملاء سكن",
    tryDifferentFilters: "حاول تعديل الفلاتر",
    createProfileToMatch: "أنشئ ملفاً لرؤية نسب التوافق",
    createProfileHint: "أكمل ملف زميل السكن للتطابق مع الآخرين",
    createProfile: "إنشاء ملف",
    anySleepSchedule: "أي جدول نوم",
    anySmoking: "أي تفضيل للتدخين",
    pendingRequests: "الطلبات المعلقة",
    acceptedMatches: "التطابقات المقبولة",
    sentRequests: "الطلبات المرسلة",
    compatible: "متوافق",
    accept: "قبول",
    reject: "رفض",
    matched: "تم التطابق!",
    message: "رسالة",
    awaitingResponse: "في انتظار الرد...",
    noMatchesYet: "لا توجد تطابقات بعد",
    startConnecting: "ابدأ التواصل مع زملاء السكن المحتملين",
    sendMatchRequest: "إرسال طلب تطابق",
    matchRequestHint: "أرسل رسالة ترحيب ودية إلى {{name}}",
    matchRequestHintPre: "أرسل رسالة ترحيب ودية إلى",
    introMessagePlaceholder: "مرحباً! أبحث عن زميل سكن وأعتقد أننا قد نكون تطابقاً جيداً...",
    sendRequest: "إرسال الطلب",
    viewProfile: "عرض الملف الشخصي",
    profileDetails: "تفاصيل الملف الشخصي",
    viewDetails: "عرض التفاصيل",
    aboutMe: "عني",
    // Majors & Interests
    major: "التخصص",
    selectMajor: "اختر تخصصك",
    interests: "الاهتمامات",
    selectInterests: "اختر اهتماماتك",
    // Common Majors
    majorEngineering: "الهندسة",
    majorComputerScience: "علوم الحاسوب",
    majorMedicine: "الطب",
    majorBusiness: "إدارة الأعمال",
    majorLaw: "القانون",
    majorArts: "الفنون والتصميم",
    majorScience: "العلوم الطبيعية",
    majorEducation: "التربية",
    majorPsychology: "علم النفس",
    majorCommunications: "الاتصال",
    majorArchitecture: "الهندسة المعمارية",
    majorNursing: "التمريض",
    majorOther: "أخرى",
    // Common Interests
    interestSports: "الرياضة",
    interestGaming: "الألعاب",
    interestReading: "القراءة",
    interestMusic: "الموسيقى",
    interestCooking: "الطبخ",
    interestFitness: "اللياقة البدنية",
    interestMovies: "الأفلام والمسلسلات",
    interestTravel: "السفر",
    interestPhotography: "التصوير",
    interestArt: "الفن",
    interestOutdoors: "الأنشطة الخارجية",
    interestTech: "التكنولوجيا",
    interestFashion: "الموضة",
    interestPets: "الحيوانات الأليفة",
    interestVolunteering: "التطوع",
    anyMajor: "أي تخصص",
    selected: "مختار",
    // Additional Roommate & Notification Keys
    cleanliness: "النظافة",
    noise: "الضوضاء",
    sleep: "النوم",
    study: "الدراسة",
    noBioProvided: "لم يتم إضافة نبذة بعد",
    noInterests: "لم يتم اختيار اهتمامات",
    pending: "قيد الانتظار",
    accepted: "مقبول",
    rejected: "مرفوض",
    newRoommateRequest: "طلب زميل سكن جديد",
    roommateRequestAccepted: "تم قبول طلب زميل السكن!",
    roommateRequestDeclined: "تم رفض طلب زميل السكن",
    compatibility: "التوافق",
    matchScore: "نسبة التطابق",
    viewFullProfile: "عرض الملف الكامل",
    roommateDetails: "تفاصيل زميل السكن",
    preferencesMatch: "تطابق التفضيلات",
    backToSearch: "العودة للبحث",
    loadingRoommateProfile: "جارٍ تحميل ملف زميل السكن...",
    roommateNotFound: "لم يتم العثور على زميل السكن",
    // Notification specific
    notificationNewMessage: "رسالة جديدة",
    notificationMatchRequest: "طلب تطابق",
    notificationMatchAccepted: "تم قبول التطابق",
    markAsRead: "تحديد كمقروء",
    allNotifications: "جميع الإشعارات",
    unreadNotifications: "غير مقروءة",
    noUnreadNotifications: "لا توجد إشعارات غير مقروءة",
    notificationsLoading: "جارٍ تحميل الإشعارات...",
    messagesLoading: "جارٍ تحميل الرسائل...",
    back: "رجوع",
    guests: "الضيوف",
    matchRequestSent: "تم إرسال طلب التطابق!",
    // Matching Priorities
    matchingPriorities: "أولويات التطابق",
    matchingPrioritiesSubtitle: "خصص ما يهمك أكثر في زميل السكن",
    priorityBudget: "الميزانية",
    priorityCleanliness: "النظافة",
    priorityNoise: "مستوى الضوضاء",
    prioritySleepSchedule: "جدول النوم",
    priorityStudyHabits: "عادات الدراسة",
    priorityInterests: "الاهتمامات المشتركة",
    priorityMajor: "نفس التخصص",
    prioritySmoking: "سياسة التدخين",
    priorityPets: "سياسة الحيوانات",
    priorityGuests: "سياسة الضيوف",
    priorityNotImportant: "غير مهم",
    prioritySlightlyImportant: "قليل الأهمية",
    priorityModerate: "متوسط",
    priorityImportant: "مهم",
    priorityVeryImportant: "مهم جداً",
    // Inactive Profile Warning
    profileInactiveWarning: "ملفك الشخصي غير نشط",
    profileInactiveHint: "قم بتفعيل ملفك الشخصي للبحث والتواصل مع زملاء السكن",
    activateProfile: "تفعيل الملف الشخصي",
    // Cost Calculator
    smartCostCalculator: "حاسبة التكلفة الذكية",
    planYourBudget: "خطط ميزانيتك",
    rentAndContract: "الإيجار والعقد",
    monthlyRent: "الإيجار الشهري",
    advanceRent: "الإيجار المقدم",
    advanceRentTooltip: "عدد أشهر الإيجار المدفوعة مقدماً.",
    monthShort: "شهر",
    roommatesExcludingYou: "زملاء السكن (باستثنائك)",
    utilitiesMonthly: "المرافق (شهرياً)",
    splitWith: "تقسيم مع",
    electricity: "الكهرباء",
    water: "المياه",
    internet: "الإنترنت",
    movingAndEssentials: "الانتقال والأساسيات",
    transport: "النقل",
    movingTruck: "شاحنة نقل",
    essentials: "الأساسيات",
    bedding: "المفروشات",
    internetSetup: "تركيب الإنترنت",
    emergencyBuffer: "احتياطي الطوارئ (10%)",
    totalMoveIn: "إجمالي الانتقال",
    upfrontRent: "الإيجار المقدم",
    deposit: "التأمين",
    monthly: "شهرياً",
    sameMajor: "نفس التخصص",
    // Verification Upload & Status
    verificationUpload: "رفع وثيقة التحقق",
    dragDropDocument: "اسحب وأفلت وثيقتك هنا، أو انقر للاختيار",
    supportedFormats: "الصيغ المدعومة",
    maxFileSize: "الحد الأقصى لحجم الملف",
    selectedFile: "الملف المختار",
    uploadToCloud: "رفع إلى السحابة",
    uploading: "جارٍ الرفع...",
    verificationStatusTitle: "حالة التحقق من الهوية",
    verificationVerified: "تم التحقق",
    verificationVerifiedDesc: "تم التحقق من هويتك بنجاح. سيتم عرض شارة \"مُوَثَّق\" على قوائمك.",
    verificationPending: "قيد المراجعة",
    verificationPendingDesc: "طلبك قيد المراجعة من قبل فريقنا. سنُعلمك قريباً!",
    verificationRejected: "مرفوض",
    verificationRejectedDesc: "طلبك السابق لم يُقبل.",
    verificationNone: "غير موثق",
    verificationNoneDesc: "قدّم وثائقك للتحقق من هويتك وبناء الثقة مع المستأجرين المحتملين.",
    documentTypeLabel: "نوع الوثيقة",
    documentTypePassport: "جواز السفر",
    documentTypeNationalId: "بطاقة الهوية الوطنية",
    documentTypeDriverLicense: "رخصة القيادة",
    submitVerification: "إرسال للتحقق",
    resubmitVerification: "إعادة الإرسال للتحقق",
    submitting: "جارٍ الإرسال...",
    // Verification Prompt
    verifyYourIdentity: "وثّق هويتك!",
    verificationBenefit1: "قوائم أكثر ظهوراً في نتائج البحث",
    verificationBenefit2: "بناء الثقة مع المستأجرين المحتملين",
    verificationBenefit3: "وصول أسرع إلى الميزات المتقدمة",
    verificationBenefit4: "شارة \"مُوَثَّق\" على ملفك الشخصي",
    verifyNow: "التوثيق الآن",
    remindLater: "ذكّرني لاحقاً",
    dontShowAgain: "لا تظهر مرة أخرى",
    // Profile Verification Section
    identityVerificationTitle: "التحقق من الهوية",
    verificationStatusVerified: "موثق ✓",
    verificationStatusVerifiedDesc: "تم التحقق من هويتك بنجاح.",
    verificationStatusPending: "قيد المراجعة",
    verificationStatusPendingDesc: "طلب التحقق الخاص بك قيد المراجعة.",
    verificationStatusRejected: "مرفوض",
    verificationStatusRejectedDesc: "طلبك السابق لم يُقبل. يمكنك تقديم طلب جديد.",
    verificationStatusNone: "غير موثق",
    verificationStatusNoneDesc: "تحقق من هويتك لبناء الثقة مع المستأجرين.",
    getVerified: "التوثيق",
    viewStatus: "عرض الحالة",
    reapply: "إعادة التقديم",
    // Admin Verification Page
    adminVerificationManagement: "إدارة التحقق من الهوية",
    adminVerificationSubtitle: "مراجعة وإدارة طلبات التحقق من هوية الملاك",
    filterPending: "قيد الانتظار",
    filterApproved: "مقبول",
    filterRejected: "مرفوض",
    noVerificationRequestsFound: "لم يتم العثور على طلبات {status}",
    documentTypeLabel: "نوع الوثيقة",
    submittedOn: "تاريخ الإرسال",
    viewDocument: "عرض الوثيقة",
    reviewNotesLabel: "ملاحظات المراجعة",
    approve: "قبول",
    approveVerification: "قبول طلب التحقق",
    rejectVerification: "رفض طلب التحقق",
    confirmApproveMessage: "هل أنت متأكد من قبول طلب التحقق من",
    confirmRejectMessage: "هل أنت متأكد من رفض طلب التحقق من",
    reviewNotesOptional: "ملاحظات المراجعة (اختياري)",
    reviewNotesPlaceholder: "أضف ملاحظات حول هذا القرار...",
    processing: "جارٍ المعالجة...",
    verificationApprovedSuccess: "تم قبول طلب التحقق بنجاح",
    verificationRejectedSuccess: "تم رفض طلب التحقق",
    failedToReviewRequest: "فشل في معالجة الطلب",
    failedToLoadVerificationRequests: "فشل في تحميل طلبات التحقق",
    ok: "حسناً",
    // Admin Menu
    verification: "التحقق من الهوية",
    // Admin Announcements
    systemAnnouncements: "إعلانات النظام",
    sendAnnouncementsDescription: "إرسال إعلانات على مستوى النظام للمستخدمين",
    announcementTitle: "أدخل عنوان الإعلان",
    announcementMessage: "أدخل رسالة الإعلان",
    targetAudience: "الجمهور المستهدف",
    allUsers: "جميع المستخدمين",
    sendToEveryone: "إرسال للجميع",
    byRole: "حسب الدور",
    targetSpecificRole: "استهداف دور محدد",
    byUniversity: "حسب الجامعة",
    targetUniversity: "استهداف جامعة",
    selectRole: "اختر الدور",
    students: "الطلاب",
    landlords: "أصحاب العقارات",
    admins: "المشرفون",
    pleaseSelectTarget: "الرجاء تحديد هدف لهذا الإعلان",
    announcementSent: "تم إرسال الإعلان بنجاح إلى",
    failedToSendAnnouncement: "فشل في إرسال الإعلان",
    sendAnnouncement: "إرسال الإعلان",
    announcements: "الإعلانات",
    // Community (formerly Forum)
    community: "المجتمع",
    communityDescription: "تواصل مع الطلاب، شارك التجارب، واحصل على المشورة",
    forum: "المنتدى",
    forumDescription: "تواصل مع المجتمع، شارك التجارب، واحصل على المشورة",
    createPost: "إنشاء منشور",
    searchCommunity: "البحث في المجتمع...",
    searchForum: "البحث في المنتدى...",
    sortBy: "ترتيب حسب",
    newest: "الأحدث",
    mostViewed: "الأكثر مشاهدة",
    popular: "الأكثر شعبية",
    categories: "التصنيفات",
    all: "الكل",
    general: "عام",
    housing: "السكن",
    tips: "نصائح",
    questions: "أسئلة",
    noPostsFound: "لم يتم العثور على منشورات",
    myPosts: "منشوراتي",
    noMyPostsYet: "لم تنشر أي شيء بعد",
    createYourFirstPost: "أنشئ أول منشور لك",
    createFirstPost: "كن أول من ينشر!",
    pinned: "مثبت",
    locked: "مقفل",
    upvote: "تصويت إيجابي",
    downvote: "تصويت سلبي",
    views: "مشاهدة",
    comments: "تعليقات",
    backToCommunity: "العودة للمجتمع",
    minsAgo: "د",
    hoursAgo: "س",
    daysAgo: "ي",
    justNow: "الآن",
    backToForum: "العودة للمنتدى",
    postNotFound: "المنشور غير موجود",
    editPost: "تعديل المنشور",
    post: "نشر",
    posting: "جارٍ النشر...",
    postComment: "نشر تعليق",
    noCommentsYet: "لا توجد تعليقات بعد",
    addComment: "اكتب تعليقاً...",
    confirmDeletePost: "هل أنت متأكد من حذف هذا المنشور؟",
    confirmDeleteComment: "هل أنت متأكد من حذف هذا التعليق؟",
    pin: "تثبيت",
    unpin: "إلغاء التثبيت",
    lock: "قفل",
    unlock: "فتح",
    postIsLocked: "هذا المنشور مقفل ولا يمكن التعليق عليه.",
    titleAndContentRequired: "العنوان والمحتوى مطلوبان",
    failedToCreatePost: "فشل في إنشاء المنشور",
    enterPostTitle: "أدخل عنواناً جذاباً...",
    enterPostContent: "شارك أف كارك، أسئلتك، أو تجاربك...",
    // Reviews
    reviews: "التقييمات",
    writeReview: "كتابة تقييم",
    review: "تقييم",
    rating: "التقييم",
    ratingDistribution: "توزيع التقييمات",
    beTheFirst: "كن أول من يقيّم!",
    noReviewsYet: "لا توجد تقييمات بعد",
    pleaseSelectRating: "الرجاء اختيار تقييم",
    commentRequired: "تعليق التقييم مطلوب",
    failedToSubmitReview: "فشل في إرسال التقييم",
    submitReview: "إرسال التقييم",
    editReview: "تعديل التقييم",
    reviewTitlePlaceholder: "لخص تجربتك...",
    reviewCommentPlaceholder: "شارك تفاصيل عن تجربتك...",
    prosPlaceholder: "ما الذي أعجبك؟",
    consPlaceholder: "ما الذي يمكن تحسينه؟",
    yourReview: "تقييمك",
    confirmDeleteReview: "هل أنت متأكد من حذف هذا التقييم؟",
    optional: "اختياري",
    helpful: "مفيد",
    deletePost: "حذف المنشور",
    deleteComment: "حذف التعليق",
    deleteReview: "حذف التقييم",
    pros: "الإيجابيات",
    cons: "السلبيات",
    // Marketplace
    studentMarketplace: "سوق الطلاب",
    marketplaceDescription: "بيع وشراء الأغراض مع زملائك الطلاب",
    searchMarketplace: "البحث عن أغراض...",
    latestItems: "أحدث الأغراض",
    myItems: "أغراضي",
    postItem: "نشر غرض",
    noItemsFound: "لم يتم العثور على أغراض",
    noMyItemsYet: "لم تنشر أي أغراض بعد",
    postYourFirstItem: "انشر أول غرض للبيع",
    deleteItemConfirm: "هل أنت متأكد من حذف هذا الغرض؟ لا يمكن التراجع عن هذا الإجراء.",
    items: "أغراض",
    failedToLoadItems: "فشل في تحميل الأغراض",
    failedToCreateItem: "فشل في نشر الغرض",
    itemCreatedSuccessfully: "تم نشر الغرض بنجاح!",
    itemUpdatedSuccessfully: "تم تحديث الغرض بنجاح!",
    editItem: "تعديل الغرض",
    pleaseSignInToPostItem: "الرجاء تسجيل الدخول لنشر أغراض للبيع.",
    pleaseSignInToViewMarketplace: "الرجاء تسجيل الدخول لعرض السوق.",
    accessRestricted: "الوصول محدود",
    marketplaceLandlordRestricted: "السوق متاح للطلاب فقط. كمالك عقار، يمكنك إدارة عقاراتك في قسم الشقق.",
    goToApartments: "الذهاب للشقق",
    // Categories
    category: "الفئة",
    categoryFurniture: "أثاث",
    categoryElectronics: "إلكترونيات",
    categoryBooks: "كتب",
    categoryClothing: "ملابس",
    categoryKitchenware: "أدوات مطبخ",
    categorySports: "رياضة",
    categoryOther: "أخرى",
    // Conditions
    condition: "الحالة",
    conditionNew: "جديد",
    conditionLikeNew: "شبه جديد",
    conditionGood: "جيد",
    conditionFair: "مقبول",
    // Item form
    itemTitlePlaceholder: "ماذا تبيع؟",
    itemDescriptionPlaceholder: "صف الغرض...",
    contactPhone: "هاتف التواصل",
    contactEmail: "بريد التواصل",
    remaining: "متبقي",
    // Item details
    sellerInfo: "معلومات البائع",
    itemNotFound: "الغرض غير موجود",
    failedToLoadItem: "فشل في تحميل الغرض",
    // Landlord Features - Viewings
    landlordDashboard: "لوحة تحكم المالك",
    manageAvailability: "إدارة التوفر",
    availability: "التوفر",
    upcomingViewings: "المعاينات القادمة",
    scheduleViewing: "جدولة معاينة",
    viewingDate: "تاريخ المعاينة",
    viewingTime: "وقت المعاينة",
    viewingStatus: "الحالة",
    viewingNotes: "ملاحظات",
    confirmViewing: "تأكيد",
    cancelViewing: "إلغاء المعاينة",
    noViewingsScheduled: "لا توجد معاينات مجدولة",
    viewingConfirmed: "تم تأكيد المعاينة",
    viewingCancelled: "تم إلغاء المعاينة",
    viewingPending: "قيد الانتظار",
    viewingCompleted: "مكتملة",
    viewingNoShow: "لم يحضر",
    bookViewing: "حجز معاينة",
    selectDate: "اختر التاريخ",
    selectTime: "اختر الوقت",
    studentNotes: "ملاحظاتك",
    studentNotesPlaceholder: "أي أسئلة أو طلبات خاصة؟",
    viewingBooked: "تم حجز المعاينة بنجاح!",
    viewingRequestSent: "تم إرسال طلب المعاينة للمالك",
    failedToBookViewing: "فشل في حجز المعاينة",
    setAvailability: "تعيين التوفر",
    weeklyAvailability: "التوفر الأسبوعي",
    sunday: "الأحد",
    monday: "الاثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    startTime: "وقت البداية",
    endTime: "وقت النهاية",
    addTimeSlot: "إضافة فترة زمنية",
    availabilityUpdated: "تم تحديث التوفر بنجاح",
    noAvailability: "لم يتم تعيين توفر",
    failedToLoadAvailability: "فشل في تحميل التوفر",
    // Landlord Features - Analytics
    analytics: "التحليلات",
    totalViews: "إجمالي المشاهدات",
    totalFavorites: "إجمالي المفضلات",
    totalInquiries: "إجمالي الاستفسارات",
    propertiesCount: "العقارات النشطة",
    performanceTrends: "اتجاهات الأداء",
    propertyPerformance: "أداء العقار",
    last30Days: "آخر 30 يوماً",
    viewsOverTime: "المشاهدات عبر الوقت",
    favoritesOverTime: "المفضلات عبر الوقت",
    inquiriesOverTime: "الاستفسارات عبر الوقت",
    noAnalyticsData: "لا توجد بيانات تحليلية",
    failedToLoadAnalytics: "فشل في تحميل التحليلات",
    propertyAnalytics: "تحليلات العقار",
    dailyStats: "الإحصائيات اليومية",
    engagementRate: "معدل التفاعل",
    conversionRate: "معدل التحويل",
    // Landlord Features - Price History
    priceHistory: "سجل الأسعار",
    priceChanges: "تغيرات السعر",
    currentPrice: "السعر الحالي",
    previousPrice: "السعر السابق",
    priceIncrease: "زيادة السعر",
    priceDecrease: "انخفاض السعر",
    priceChange: "تغيير السعر",
    changePercentage: "التغيير",
    recordedAt: "التاريخ",
    initialPrice: "السعر الأولي",
    noPriceHistory: "لم يتم تسجيل تغييرات في السعر",
    failedToLoadPriceHistory: "فشل في تحميل سجل الأسعار",
    // Landlord Features - Market Insights
    marketInsights: "رؤى السوق",
    averagePrice: "متوسط السعر",
    marketTrends: "اتجاهات السوق",
    priceComparison: "مقارنة الأسعار",
    byPropertyType: "حسب نوع العقار",
    nearUniversity: "بالقرب من الجامعة",
    marketAverage: "متوسط السوق",
    yourPrice: "سعرك",
    competitive: "تنافسي",
    aboveMarket: "أعلى من السوق",
    belowMarket: "أقل من السوق",
    // Common
    today: "اليوم",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    yesterday: "الأمس",
    dateRange: "نطاق التاريخ",
    noDataAvailable: "لا توجد بيانات متاحة",
    // New pages - Price History & Reviews
    viewPriceHistory: "عرض سجل الأسعار",
    trackPriceChanges: "تتبع تغييرات أسعار عقارك عبر الوقت",
    seeAllReviews: "عرض جميع التقييمات",
    allReviews: "جميع التقييمات",
    averageRating: "متوسط التقييم",
    totalChange: "إجمالي التغيير",
    foundHelpful: "أشخاص وجدوا هذا مفيداً",
    goBack: "رجوع",
    unauthorized: "غير مصرح لك بعرض هذه الصفحة",
    prices: "الأسعار",
    viewingBookedSuccess: "تم حجز المعاينة بنجاح! سيتم إبلاغ المالك.",
    // Distance Filter
    allUniversities: "جميع الجامعات",
    distanceFromUniversity: "المسافة من الجامعة",
    propertyVideo: "فيديو العقار",
    distanceAway: "بعيد",
    // Nearby Places
    nearbyPlaces: "الأماكن القريبة",
    showOnMap: "إظهار على الخريطة",
    propertiesOnMap: "عقارات على الخريطة",
    supermarket: "سوبرماركت",
    restaurant: "مطاعم",
    pharmacy: "صيدليات",
    bank: "بنوك",
    bus_station: "محطات الباصات",
    cafe: "مقاهي",
    distance200m: "200 متر",
    distance500m: "500 متر",
    distance1km: "1 كم",
    distance2km: "2 كم",
    distance5km: "5 كم",
    distanceHint: "عرض العقارات ضمن هذا النطاق",
    selectUniversityForDistance: "اختر جامعة أولاً للتصفية حسب المسافة",
    // Reports
    reportsManagement: "إدارة البلاغات",
    reportsManagementSubtitle: "مراجعة وإدارة بلاغات المستخدمين",
    reportUser: "الإبلاغ عن مستخدم",
    reportReasonSpam: "رسائل مزعجة",
    reportReasonHarassment: "تحرش",
    reportReasonInappropriate: "محتوى غير لائق",
    reportReasonScam: "احتيال أو نصب",
    reportReasonHateSpeech: "خطاب كراهية",
    reportReasonThreats: "تهديدات",
    reportReasonOther: "أخرى",
    selectReportReason: "يرجى اختيار سبب",
    reportFailed: "فشل في إرسال البلاغ",
    reportSubmitted: "تم إرسال البلاغ بنجاح",
    reportReviewMessage: "سيقوم فريقنا بمراجعة هذا البلاغ",
    reportDescription: "الإبلاغ عن سلوك غير لائق",
    additionalDetails: "تفاصيل إضافية",
    reportDetailsPlaceholder: "قدم أي سياق إضافي...",
    submitReport: "إرسال البلاغ",
    failedToLoadReports: "فشل في تحميل البلاغات",
    failedToLoadReportDetails: "فشل في تحميل تفاصيل البلاغ",
    noReportsFound: "لم يتم العثور على بلاغات",
    reportStatusPending: "قيد الانتظار",
    reportStatusReviewed: "تمت المراجعة",
    reportStatusResolved: "تم الحل",
    reportStatusDismissed: "مرفوض",
    reportActionNone: "لا إجراء",
    reportActionWarning: "تحذير",
    reportActionSuspended: "موقوف",
    reportActionBanned: "محظور",
    reportedBy: "أبلغ عنه",
    reportedUser: "المستخدم المُبلغ عنه",
    reportedMessage: "الرسالة المُبلغ عنها",
    adminNotes: "ملاحظات المشرف",
    adminNotesPlaceholder: "أضف ملاحظات داخلية حول هذا القرار...",
    reportDetails: "تفاصيل البلاغ",
    reportInfo: "معلومات البلاغ",
    conversationHistory: "سجل المحادثة",
    dismissReport: "رفض البلاغ",
    sendWarningTitle: "إرسال تحذير",
    suspendUserTitle: "إيقاف المستخدم",
    banUserTitle: "حظر المستخدم",
    confirmDismissReport: "هل أنت متأكد من رفض هذا البلاغ؟",
    confirmSendWarning: "إرسال تحذير إلى",
    confirmSuspendUser: "إيقاف المراسلة لـ",
    confirmBanUser: "حظر المستخدم",
    warningMessage: "رسالة التحذير",
    warningMessagePlaceholder: "أدخل رسالة التحذير لإرسالها للمستخدم...",
    sendWarning: "إرسال تحذير",
    suspendUser: "إيقاف",
    banUser: "حظر",
    reportActionSuccess: "تم تنفيذ إجراء البلاغ بنجاح",
    failedToProcessReport: "فشل في معالجة البلاغ",
    userUnsuspended: "تم إلغاء إيقاف مراسلة المستخدم بنجاح",
    failedToUnsuspendUser: "فشل في إلغاء إيقاف المستخدم",
    close: "إغلاق",
    error: "خطأ",
    // AI Chat
    aiChatNewChat: "محادثة جديدة",
    aiChatNoConversationsYet: "لا توجد محادثات بعد",
    aiChatStartChatting: "ابدأ المحادثة لإنشاء واحدة!",
    aiChatRecentChats: "المحادثات الأخيرة",
    aiChatDeleteConversation: "حذف المحادثة",
    aiChatDeleteConversationTitle: "حذف المحادثة؟",
    aiChatDeleteConversationMessage: "هل أنت متأكد من حذف هذه المحادثة؟ لا يمكن التراجع عن هذا الإجراء.",
    aiChatUniNestAssistant: "مساعد UniNest",
    aiChatPropertyExpert: "خبير العقارات",
    aiChatYourCaringAssistant: "مساعدك المهتم",
    aiChatPropertyMarketingExpert: "خبير تسويق العقارات",
    aiChatWhatCanIHelp: "كيف يمكنني المساعدة؟",
    aiChatHowCanIHelpProperty: "كيف يمكنني مساعدة عقارك؟",
    aiChatStudentDescription: "اسألني عن الطبخ، التنظيف، الميزانية، أو أي نصائح للحياة الطلابية!",
    aiChatLandlordDescription: "احصل على نصائح الخبراء حول التسويق والتسعير وإدارة المستأجرين.",
    aiChatAskMeAnything: "اسألني أي شيء...",
    aiChatHowCanIHelpPropertyInput: "كيف يمكنني المساعدة في عقارك؟",
    aiChatCanMakeMistakes: "قد يرتكب أخطاء. يرجى التحقق من المعلومات المهمة.",
    aiChatNewConversation: "محادثة جديدة",
    aiChatJustNow: "الآن",
    aiChatMinutesAgo: "د",
    aiChatHoursAgo: "س",
    aiChatDaysAgo: "ي",
    aiChatMessages: "رسالة",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Initialize from localStorage or default to 'en'
    return localStorage.getItem("preferredLanguage") || "en";
  });
  const [isChangingLanguage, setIsChangingLanguage] = useState(false);

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
    // Persist language to localStorage
    localStorage.setItem("preferredLanguage", language);
  }, [language]);

  const toggleLanguage = () => {
    setIsChangingLanguage(true);
    // Small delay for smooth transition
    setTimeout(() => {
      setLanguage((prev) => (prev === "en" ? "ar" : "en"));
      setTimeout(() => {
        setIsChangingLanguage(false);
      }, 100);
    }, 150);
  };

  const changeLanguage = (lang) => {
    if (lang === "en" || lang === "ar") {
      setIsChangingLanguage(true);
      setTimeout(() => {
        console.log("Changing language to:", lang);
        setLanguage(lang);
        setTimeout(() => {
          setIsChangingLanguage(false);
        }, 100);
      }, 150);
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, toggleLanguage, changeLanguage, t, isChangingLanguage }}
    >
      {isChangingLanguage && (
        <div className="fixed inset-0 z-[9999] bg-[var(--color-surface)]/80 backdrop-blur-sm flex items-center justify-center">
          <div className="flex flex-col items-center gap-4">
            <div className="w-12 h-12 border-4 border-[var(--color-accent)]/30 border-t-[var(--color-accent)] rounded-full animate-spin"></div>
            <p className="text-[var(--color-text)] font-medium">
              {language === "en" ? "Switching language..." : "جارٍ تبديل اللغة..."}
            </p>
          </div>
        </div>
      )}
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
